### ISSUE TITLE
3.11 - test coverage

### ISSUE THREAD

**Issue by aspark21** [paulholden/moodle-local_cohortrole#9]
Warning: $whitelistfolders and $whitelistfiles in coverage.php files are deprecated since Moodle 3.11. Please, replace them with $includelistfolders and $includelistfiles in local/cohortrole/tests/coverage.php

Occurs towards the end of environment setup for phpunit

**Comment by paulholden** [comment]
Cheers @aspark21 - will require a change similar to https://github.com/paulholden/moodle-report_upgradelog/commit/4a9536ffd3f1a4e25650e6777fb793977cd7665b#diff-dd2a88e07bd10dc7e09640732f4a73f9c8110cde7da1357d3ed2768cf4837173 - patches welcome :)

I'll do this as part of the 3.11 version bump otherwise
